version: "3.1"
services:
  publisher:
    build: ./
    network_mode: "host" # required for bluez to work and to publish mqtt topics
    privileged: true # required for bluez to work
    restart: unless-stopped
    environment:
      MQTT_BROKER_ADDRESS: ""
      MQTT_BROKER_PORT: 1883 
      MQTT_BROKER_USERNAME: ""
      MQTT_BROKER_PASSWORD: ""
      LOG_LEVEL: INFO # DEBUG, INFO, WARNING, ERROR, CRITICAL
